version: '2'
services:

  web:
    image: nginx
    ports:
      - "8089:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - code

  php:
    build: .
    working_dir: /var/www
    volumes_from:
      - code

  code:
    image: busybox
    volumes:
      - ./www:/var/www
